### ISSUE TITLE
Add these features to results_parser.py

### ISSUE THREAD

**Issue by rosscutler** [microsoft/P.910#2]
- Don't use HITS with raters with < X% accuracy and >= N hits, e.g., X=80%, N=5
- Create a list of low-performance raters to ban

Update documentation in https://github.com/microsoft/P.910/blob/main/docs/results.md.

**Comment by babaknaderi** [comment]
Done in commit [7150773](https://github.com/microsoft/P.910/commit/7150773a57d0026ea649c7e271ed8a3c8703a1f3)
